# Generated by Django 2.2.10 on 2020-02-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=200)),
                ('email_recipients', models.CharField(max_length=300, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Prospects',
            },
        ),
        migrations.CreateModel(
            name='RunDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('prospect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospect.Prospect')),
            ],
            options={
                'verbose_name_plural': 'Run_Details',
            },
        ),
    ]
