# Generated by Django 2.2.10 on 2020-02-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='file_name',
            field=models.FileField(upload_to='prospect_input'),
        ),
    ]
