# Generated by Django 2.2.10 on 2020-02-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0002_auto_20200204_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='run_count',
            field=models.IntegerField(default=0),
        ),
    ]
