# Generated by Django 2.2.10 on 2020-02-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0004_prospect_other_column_header_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='other_column_header_list',
        ),
    ]
