# Generated by Django 2.2.10 on 2020-02-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0005_remove_prospect_other_column_header_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rundetails',
            old_name='prospect_id',
            new_name='prospect',
        ),
        migrations.AddField(
            model_name='rundetails',
            name='batch_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rundetails',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rundetails',
            name='total_pla_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rundetails',
            name='total_showcase_records',
            field=models.IntegerField(default=0),
        ),
    ]
