# Generated by Django 2.2.10 on 2020-02-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0007_rundetails_post_process_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundetails',
            name='file_size',
            field=models.CharField(default='0 KB', max_length=50),
        ),
    ]
