# Generated by Django 2.2.10 on 2020-02-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0008_auto_20200206_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='platform',
            field=models.CharField(choices=[('Google', 'Google'), ('Amazon', 'Amazon')], default='Google', max_length=20),
            preserve_default=False,
        ),
    ]
