# Generated by Django 2.2.10 on 2020-02-12 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0009_prospect_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('total_amazon_choices_records', models.IntegerField(default=0)),
                ('total_brands_related_records', models.IntegerField(default=0)),
                ('total_editorial_recommendations_records', models.IntegerField(default=0)),
                ('total_organic_records', models.IntegerField(default=0)),
                ('total_sponsored_records', models.IntegerField(default=0)),
                ('total_today_deals_records', models.IntegerField(default=0)),
                ('post_process_completed', models.BooleanField(default=False)),
                ('batch_email_sent', models.BooleanField(default=False)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospect.Prospect')),
            ],
            options={
                'verbose_name_plural': 'Amazon_Run_Details',
            },
        ),
    ]
