# Generated by Django 2.2.10 on 2020-02-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0011_auto_20200212_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rundetails',
            options={'verbose_name_plural': 'Google_Run_Details'},
        ),
    ]
